namespace: staging

replicaCount: 3

image:
  repository: snigdha2017/techtrends
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: regcred   # secret dockerhub secret

service:
  port: 5111
  targetPort: 3111
  protocol: TCP

resources:
  requests:
    cpu: 300m
    memory: 90Mi
  limits:
    cpu: 500m
    memory: 128Mi